package pvr;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import mx.venado.pvr.controlador.PvrVenta;
import mx.venado.pvr.utilidades.FuenteUbuntu;
import mx.venado.pvr.vista.ModeloVenta;
import mx.venado.pvr.vista.ModeloVentaBusqueda;
import mx.venado.pvr.vista.TableCellRendererVenta;

public class DfrmProductosVentas extends javax.swing.JDialog {

    ModeloVentaBusqueda modeloBusqueda;
    
    public DfrmProductosVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ConfigForm(parent);
    }
    
    private void ConfigForm(java.awt.Frame parent) {
        this.setLocationRelativeTo(parent);
        this.setTitle("Doble clic para seleccionar el producto");
        modeloBusqueda = new ModeloVentaBusqueda();
        tblBusqueda.setDefaultRenderer(Object.class, new TableCellRendererVenta());
        tblBusqueda.setModel(modeloBusqueda);
        tblBusqueda.setRowHeight(50);
        tblBusqueda.getTableHeader().setFont(new FuenteUbuntu().AplicarLightFont());
        tblBusqueda.getColumnModel().getColumn(0).setMaxWidth(50);
    }
    
    public void SetDatos(ArrayList<Object[]> list){
        for (int i = 0; i < list.size(); i++) {
            modeloBusqueda.addRow(list.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusqueda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        tblBusqueda.setFont(new FuenteUbuntu().AplicarRegularFont(15));
        tblBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBusqueda.setSelectionBackground(new java.awt.Color(245, 245, 245));
        tblBusqueda.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblBusqueda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusquedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusqueda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusquedaMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tblBusqueda.getSelectedRow();
            if (fila != -1) {
                PvrVenta.idSeleccionBusqueda = fila;
                this.dispose();
            }
        }
    }//GEN-LAST:event_tblBusquedaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DfrmProductosVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DfrmProductosVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DfrmProductosVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DfrmProductosVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DfrmProductosVentas dialog = new DfrmProductosVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBusqueda;
    // End of variables declaration//GEN-END:variables
}
